# Compile a reviewed replacement without changing the pinned Playerbots checkout.
set(_shuffle_dir "${CMAKE_BINARY_DIR}/playerbot_shuffle")
file(MAKE_DIRECTORY "${_shuffle_dir}")
file(READ "${playerbots_SOURCE_DIR}/playerbot/WorldPosition.cpp" _shuffle_text)
string(REPLACE "\r\n" "\n" _shuffle_text "${_shuffle_text}")
string(SHA256 _shuffle_hash "${_shuffle_text}")
if(NOT _shuffle_hash STREQUAL "fda82d89916cf95d30145658c858b46a16b4635cc9fc9ebcd00bfcfed0e70bfc")
  message(FATAL_ERROR "Review relocation shuffle: upstream WorldPosition.cpp changed")
endif()
string(REPLACE "#include \"WorldPosition.h\"" "#include \"WorldPosition.h\"\n#include \"Util/PositiveWeightedShuffle.h\"" _shuffle_text "${_shuffle_text}")
string(REPLACE "WeightedShuffle(retVec.begin(), retVec.end(), weights.begin(), weights.end(), gen);"
  "ManTech::PositiveWeightedShuffle(retVec, weights, gen);" _shuffle_text "${_shuffle_text}")
file(WRITE "${_shuffle_dir}/WorldPosition.cpp.in" "${_shuffle_text}")
configure_file("${_shuffle_dir}/WorldPosition.cpp.in" "${_shuffle_dir}/WorldPosition.cpp" COPYONLY)
get_target_property(_shuffle_sources playerbots SOURCES)
set(_shuffle_matches ${_shuffle_sources})
list(FILTER _shuffle_matches INCLUDE REGEX "(^|/)WorldPosition[.]cpp$")
list(LENGTH _shuffle_matches _shuffle_count)
if(NOT _shuffle_count EQUAL 1)
  message(FATAL_ERROR "Expected exactly one WorldPosition.cpp source")
endif()
list(REMOVE_ITEM _shuffle_sources ${_shuffle_matches})
list(APPEND _shuffle_sources "${_shuffle_dir}/WorldPosition.cpp")
set_property(TARGET playerbots PROPERTY SOURCES "${_shuffle_sources}")
set_source_files_properties("${_shuffle_dir}/WorldPosition.cpp" TARGET_DIRECTORY playerbots
  PROPERTIES INCLUDE_DIRECTORIES "${playerbots_SOURCE_DIR}/playerbot")
