# The realm loot policy belongs to the core, not to the fetched Playerbots fork.
# Refuse an unreviewed upstream change instead of silently replacing new logic.
set(_loot_original "${playerbots_SOURCE_DIR}/playerbot/strategy/actions/SecurityCheckAction.cpp")
file(READ "${_loot_original}" _loot_text)
string(REPLACE "\r\n" "\n" _loot_text "${_loot_text}")
string(SHA256 _loot_hash "${_loot_text}")
if(NOT _loot_hash STREQUAL "d75aa4540730917b016035f81ee96addcee6b874b8cae810ad52e85bc9118264")
  message(FATAL_ERROR "Playerbots SecurityCheckAction changed: review the core loot-policy override before updating its expected hash.")
endif()
get_target_property(_loot_sources playerbots SOURCES)
set(_loot_matches ${_loot_sources})
list(FILTER _loot_matches INCLUDE REGEX "(^|/)SecurityCheckAction\\.cpp$")
list(LENGTH _loot_matches _loot_count)
if(NOT _loot_count EQUAL 1)
  message(FATAL_ERROR "Expected exactly one Playerbots SecurityCheckAction source for the core loot-policy override.")
endif()
list(REMOVE_ITEM _loot_sources ${_loot_matches})
list(APPEND _loot_sources "${CMAKE_CURRENT_LIST_DIR}/../src/playerbot_overrides/LootSecurityCheckAction.cpp")
set_property(TARGET playerbots PROPERTY SOURCES "${_loot_sources}")
message(STATUS "Core loot policy: random bots accept every native group loot method")
