# Reviewed hot paths in the pinned module; preserve the upstream checkout.
set(_hot_dir "${CMAKE_BINARY_DIR}/playerbot_hotpaths")
file(MAKE_DIRECTORY "${_hot_dir}")
file(READ "${CMAKE_BINARY_DIR}/playerbot_lifecycle/PlayerbotAI.cpp" _hot_ai)
# These four loops only inspect auras. Keep GetAurasByType's stable-reference
# contract, but do not request a stable empty container for an absent type.
string(REGEX MATCHALL "(unit|target)->GetAurasByType\\(\\(AuraType\\)(auraType|type)\\)" _hot_reads "${_hot_ai}")
list(LENGTH _hot_reads _hot_count)
if(NOT _hot_count EQUAL 4)
  message(FATAL_ERROR "Review aura scan hot paths: expected four read-only loops")
endif()
string(REPLACE "Unit::AuraList const& auras = unit->GetAurasByType((AuraType)auraType);"
  "if (!unit->HasAuraType((AuraType)auraType))\n                continue;\n            Unit::AuraList const& auras = unit->GetAurasByType((AuraType)auraType);" _hot_ai "${_hot_ai}")
string(REPLACE "Unit::AuraList const& auras = target->GetAurasByType((AuraType)type);"
  "if (!target->HasAuraType((AuraType)type))\n            continue;\n        Unit::AuraList const& auras = target->GetAurasByType((AuraType)type);" _hot_ai "${_hot_ai}")

file(READ "${playerbots_SOURCE_DIR}/playerbot/ChatHelper.cpp" _hot_chat)
string(REPLACE "\r\n" "\n" _hot_chat "${_hot_chat}")
string(SHA256 _hot_hash "${_hot_chat}")
if(NOT _hot_hash STREQUAL "39a3bff8143202d5e54062d5bb8622639e1caa41cf1676c9956b52a1f88635d4")
  message(FATAL_ERROR "Review link parser hot path: pinned ChatHelper.cpp changed")
endif()
string(FIND "${_hot_chat}" "std::set<uint32> ChatHelper::ExtractAllQuestIds" _hot_start)
string(FIND "${_hot_chat}" "std::set<uint32> ChatHelper::ExtractAllSkillIds" _hot_end)
math(EXPR _hot_length "${_hot_end}-${_hot_start}")
string(SUBSTRING "${_hot_chat}" ${_hot_start} ${_hot_length} _hot_legacy)
string(REPLACE "ChatHelper::" "LegacyChatHelper::" _hot_legacy "${_hot_legacy}")
file(WRITE "${_hot_dir}/legacy_link_functions.inc" "${_hot_legacy}")
foreach(_hot_kind item quest)
  set(_hot_before "    std::regex rgx(\"H${_hot_kind}:[0-9]+\");")
  string(FIND "${_hot_chat}" "${_hot_before}" _hot_match)
  if(_hot_match EQUAL -1)
    message(FATAL_ERROR "Link parser expression changed")
  endif()
  string(REPLACE "${_hot_before}" "    if (text.find(\"H${_hot_kind}:\") == std::string::npos)\n        return ids;\n\n    // Immutable expression shared by concurrent readers, compiled once.\n    static const std::regex rgx(\"H${_hot_kind}:[0-9]+\");" _hot_chat "${_hot_chat}")
endforeach()
string(FIND "${_hot_chat}" "std::set<uint32> ChatHelper::ExtractAllQuestIds" _hot_start)
string(FIND "${_hot_chat}" "std::set<uint32> ChatHelper::ExtractAllSkillIds" _hot_end)
math(EXPR _hot_length "${_hot_end}-${_hot_start}")
string(SUBSTRING "${_hot_chat}" ${_hot_start} ${_hot_length} _hot_functions)
file(WRITE "${_hot_dir}/link_functions.inc" "${_hot_functions}")

foreach(_hot_name PlayerbotAI ChatHelper)
  if(_hot_name STREQUAL "PlayerbotAI")
    set(_hot_text "${_hot_ai}")
  else()
    set(_hot_text "${_hot_chat}")
  endif()
  file(WRITE "${_hot_dir}/${_hot_name}.cpp.in" "${_hot_text}")
  configure_file("${_hot_dir}/${_hot_name}.cpp.in" "${_hot_dir}/${_hot_name}.cpp" COPYONLY)
  get_target_property(_hot_sources playerbots SOURCES)
  set(_hot_matches ${_hot_sources})
  list(FILTER _hot_matches INCLUDE REGEX "(^|/)${_hot_name}[.]cpp$")
  list(LENGTH _hot_matches _hot_count)
  if(NOT _hot_count EQUAL 1)
    message(FATAL_ERROR "Expected one ${_hot_name}.cpp source")
  endif()
  list(REMOVE_ITEM _hot_sources ${_hot_matches})
  list(APPEND _hot_sources "${_hot_dir}/${_hot_name}.cpp")
  set_property(TARGET playerbots PROPERTY SOURCES "${_hot_sources}")
  set_source_files_properties("${_hot_dir}/${_hot_name}.cpp" TARGET_DIRECTORY playerbots
    PROPERTIES INCLUDE_DIRECTORIES "${playerbots_SOURCE_DIR}/playerbot;${playerbots_SOURCE_DIR}/playerbot/strategy")
endforeach()
