# Auxiliary membership index; retain the pinned module and ordered account list.
set(_account_dir "${CMAKE_BINARY_DIR}/playerbot_accounts")
file(MAKE_DIRECTORY "${_account_dir}")

file(READ "${playerbots_SOURCE_DIR}/playerbot/PlayerbotAIConfig.cpp" _account_text)
string(REPLACE "\r\n" "\n" _account_text "${_account_text}")
string(SHA256 _account_hash "${_account_text}")
if(NOT _account_hash STREQUAL "335a73482b1f93463ac4849311baa1637cba8263b9b25670397cd09567ad89f2")
  message(FATAL_ERROR "Review account index: pinned PlayerbotAIConfig.cpp changed")
endif()
string(REPLACE [==[return find(randomBotAccounts.begin(), randomBotAccounts.end(), id) != randomBotAccounts.end();]==] [==[return ManTech::PlayerbotAccountMembership().Contains(id);]==] _account_text "${_account_text}")
set(_account_text "#include \"Util/AccountMembershipIndex.h\"\n${_account_text}")
file(WRITE "${_account_dir}/PlayerbotAIConfig.cpp.in" "${_account_text}")
configure_file("${_account_dir}/PlayerbotAIConfig.cpp.in" "${_account_dir}/PlayerbotAIConfig.cpp" COPYONLY)
get_target_property(_account_sources playerbots SOURCES)
set(_account_matches ${_account_sources})
list(FILTER _account_matches INCLUDE REGEX "(^|/)PlayerbotAIConfig[.]cpp$")
list(LENGTH _account_matches _account_count)
if(NOT _account_count EQUAL 1)
  message(FATAL_ERROR "Expected exactly one PlayerbotAIConfig.cpp source")
endif()
list(REMOVE_ITEM _account_sources ${_account_matches})
list(APPEND _account_sources "${_account_dir}/PlayerbotAIConfig.cpp")
set_property(TARGET playerbots PROPERTY SOURCES "${_account_sources}")
set_source_files_properties("${_account_dir}/PlayerbotAIConfig.cpp" TARGET_DIRECTORY playerbots
  PROPERTIES INCLUDE_DIRECTORIES "${playerbots_SOURCE_DIR}/playerbot")

file(READ "${playerbots_SOURCE_DIR}/playerbot/RandomPlayerbotFactory.cpp" _account_text)
string(REPLACE "\r\n" "\n" _account_text "${_account_text}")
string(SHA256 _account_hash "${_account_text}")
if(NOT _account_hash STREQUAL "ab80e4c246727f4d02ef5bfadeb65938530a8062fd766f281c83370af69b32e4")
  message(FATAL_ERROR "Review account index: pinned RandomPlayerbotFactory.cpp changed")
endif()
string(REPLACE [==[sPlayerbotAIConfig.randomBotAccounts.push_back(accountId);]==] [==[ManTech::PlayerbotAccountMembership().Append(sPlayerbotAIConfig.randomBotAccounts, accountId);]==] _account_text "${_account_text}")
set(_account_text "#include \"Util/AccountMembershipIndex.h\"\n${_account_text}")
file(WRITE "${_account_dir}/RandomPlayerbotFactory.cpp.in" "${_account_text}")
configure_file("${_account_dir}/RandomPlayerbotFactory.cpp.in" "${_account_dir}/RandomPlayerbotFactory.cpp" COPYONLY)
get_target_property(_account_sources playerbots SOURCES)
set(_account_matches ${_account_sources})
list(FILTER _account_matches INCLUDE REGEX "(^|/)RandomPlayerbotFactory[.]cpp$")
list(LENGTH _account_matches _account_count)
if(NOT _account_count EQUAL 1)
  message(FATAL_ERROR "Expected exactly one RandomPlayerbotFactory.cpp source")
endif()
list(REMOVE_ITEM _account_sources ${_account_matches})
list(APPEND _account_sources "${_account_dir}/RandomPlayerbotFactory.cpp")
set_property(TARGET playerbots PROPERTY SOURCES "${_account_sources}")
set_source_files_properties("${_account_dir}/RandomPlayerbotFactory.cpp" TARGET_DIRECTORY playerbots
  PROPERTIES INCLUDE_DIRECTORIES "${playerbots_SOURCE_DIR}/playerbot")

file(READ "${playerbots_SOURCE_DIR}/playerbot/RandomPlayerbotMgr.cpp" _account_text)
string(REPLACE "\r\n" "\n" _account_text "${_account_text}")
string(SHA256 _account_hash "${_account_text}")
if(NOT _account_hash STREQUAL "57473da33d87dc2ad77a48fcd7b763304e203eaf520460f24431749ba8184bc4")
  message(FATAL_ERROR "Review account index: pinned RandomPlayerbotMgr.cpp changed")
endif()
string(REPLACE [==[sPlayerbotAIConfig.randomBotAccounts.push_back(accountId);]==] [==[ManTech::PlayerbotAccountMembership().Append(sPlayerbotAIConfig.randomBotAccounts, accountId);]==] _account_text "${_account_text}")
set(_account_text "#include \"Util/AccountMembershipIndex.h\"\n${_account_text}")
file(WRITE "${_account_dir}/RandomPlayerbotMgr.cpp.in" "${_account_text}")
configure_file("${_account_dir}/RandomPlayerbotMgr.cpp.in" "${_account_dir}/RandomPlayerbotMgr.cpp" COPYONLY)
get_target_property(_account_sources playerbots SOURCES)
set(_account_matches ${_account_sources})
list(FILTER _account_matches INCLUDE REGEX "(^|/)RandomPlayerbotMgr[.]cpp$")
list(LENGTH _account_matches _account_count)
if(NOT _account_count EQUAL 1)
  message(FATAL_ERROR "Expected exactly one RandomPlayerbotMgr.cpp source")
endif()
list(REMOVE_ITEM _account_sources ${_account_matches})
list(APPEND _account_sources "${_account_dir}/RandomPlayerbotMgr.cpp")
set_property(TARGET playerbots PROPERTY SOURCES "${_account_sources}")
set_source_files_properties("${_account_dir}/RandomPlayerbotMgr.cpp" TARGET_DIRECTORY playerbots
  PROPERTIES INCLUDE_DIRECTORIES "${playerbots_SOURCE_DIR}/playerbot")
